twig:
    default_path: '%kernel.project_dir%/templates'
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'
    form_themes: ['commun/form/fields.html.twig']
    date:
        timezone: Europe/Paris
        format: d.m.Y