<?php

namespace AcMarche\Mercredi\Admin\Repository;

use AcMarche\Mercredi\Admin\Entity\CaisseAllocation;
use Doctrine\ORM\EntityRepository;

/**
 * CaisseAllocationRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CaisseAllocationRepository extends EntityRepository
{
    /**
     * @return CaisseAllocation[]
     */
    public function findAll()
    {
        return $this->findBy([], ['nom' => 'ASC']);
    }

    /**
     * @param array $args
     *
     * @return CaisseAllocation[]
     */
    public function search($args = [])
    {
        $qb = $this->createQueryBuilder('c');
        $qb->leftJoin('c.tuteur', 't', 'WITH');
        $qb->addSelect('c', 't');

        $query = $qb->getQuery();

        $results = $query->getResult();

        return $results;
    }
}
