<?php

namespace AcMarche\Mercredi\Admin\Repository;

use Doctrine\ORM\EntityRepository;
use AcMarche\Mercredi\Admin\Entity\Reduction;

/**
 * ReductionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReductionRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy(array(), array('nom' => 'ASC'));
    }

    /**
     * @param array $args
     * @return Reduction[]
     */
    public function search($args = array())
    {
        $qb = $this->createQueryBuilder('r');
        $qb->leftJoin('r.presence', 'p', 'WITH');
        $qb->addSelect('r', 'p');

        $query = $qb->getQuery();

        $results = $query->getResult();

        return $results;
    }
}
