<?php

namespace AcMarche\Mercredi\Admin\Repository;

use AcMarche\Mercredi\Admin\Entity\Reduction;
use Doctrine\ORM\EntityRepository;

/**
 * ReductionRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ReductionRepository extends EntityRepository
{
    public function findAll()
    {
        return $this->findBy([], ['nom' => 'ASC']);
    }

    /**
     * @param array $args
     *
     * @return Reduction[]
     */
    public function search($args = [])
    {
        $qb = $this->createQueryBuilder('r');
        $qb->leftJoin('r.presence', 'p', 'WITH');
        $qb->addSelect('r', 'p');

        $query = $qb->getQuery();

        $results = $query->getResult();

        return $results;
    }
}
