<?php

namespace AcMarche\Mercredi\Plaine\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * AnimateurPlaineRepository.
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AnimateurPlaineRepository extends EntityRepository
{
}
