services:
    _defaults:
        public: true
        autowire: true      # Automatically injects dependencies in your services.

    # If you need to access services in a test, create an alias
    # and then fetch that alias from the container. As a convention,
    # aliases are prefixed with test. For example:
    #
    # test.App\Service\MyService: '@App\Service\MyService'
    AcMarche\Mercredi\Admin\Service\OrdreService:
        public: true